
// @flow
// eslint-disable
// WARNING: THIS FILE IS AUTOGENERATED BY update_type.sh
export type Translation = {
  global: {
    language: {
      chineseSimplified: string,
      chineseTraditional: string,
      english: string,
      japanese: string,
      korean: string
    },
    datetime: {
      today: string,
      yesterday: string
    }
  },
  languageSelectScreen: {
    selectLanguage: string,
    continue: string
  },
  txHistoryScreen: {
    transactionType: {
      SENT: string,
      RECEIVED: string
    },
    assuranceLevelHeader: string,
    assuranceLevel: {
      LOW: string,
      MEDIUM: string,
      HIGH: string
    },
    transactionDetails: {
      fromAddresses: string,
      toAddresses: string,
      transactionId: string,
      txAssuranceLevel: string,
      transactionHeader: {
        SENT: string,
        RECEIVED: string
      }
    }
  },
  walletInitScreen: {
    line1: string,
    line2: string,
    byEmurgo: string
  }
}
