const DEFAULT_TIMEOUT = 5000;
const DEFAULT_INTERVAL = 200;
const VALID_PIN = "123456";
const WALLET_NAME = "Testnet Wallet";
const SPENDING_PASSWORD = "1234567890";

module.exports = {
  DEFAULT_TIMEOUT,
  DEFAULT_INTERVAL,
  VALID_PIN,
  WALLET_NAME,
  SPENDING_PASSWORD
};