coverage:
  status:
    project:
      default:
        threshold: 1%
        target: 5%
        if_not_found: success
    patch:
      default:
        threshold: 1%
        target: 5%
        if_not_found: success

ignore:
  - "node_modules"
  - "dist"
  - "build"
  - "**/__tests__/**"
  - "**/*.test.*"
  - "scripts"
  - "coverage"
  - "mobile/assets"
  - "mobile/fastlane"
  - "mobile/cpp"
  - "mobile/public"
  - "mobile/plugins"
  - "mobile/scripts"
  - "**/__mocks__/**"
  - "**/*.js"
  - "mobile/index.ts"

comment:
  layout: "reach,diff"
  require_changes: true
  behavior: default
