sonar.projectKey=Emurgo_yoroi-mobile_AYXPbEkyWigj-SXq5nF2

# Define sources 
sonar.sources=apps/wallet-mobile/src

# Exclude patterns for all packages
sonar.exclusions=.github/**,.vscode/**,android/**,assets/**,build/**,e2e/**,ios/**,node_modules/**,scripts/**,tests/**,**/*.stories.tsx,**/*.test.ts,**/*.spec.js,**/*.test.tsx,**/*.spec.tsx,**/jest.config.js,**/babel.config.js,**/metro.config.js

# Coverage exclusions
sonar.coverage.exclusions=**/*.*

# Duplicate code exclusions
sonar.cpd.exclusions=**/*.*

# Test file patterns
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.tsx

# Source encoding
sonar.sourceEncoding=UTF-8