// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
	require('../legacy/components/Catalyst/Catalyst.stories');
	require('../legacy/components/Catalyst/VotingBanner.stories');
	require('../legacy/components/Common/DangerousActionModal.stories');
	require('../legacy/components/Common/ErrorModal.stories');
	require('../legacy/components/Common/ExpandableItem.stories');
	require('../legacy/components/Common/FingerprinScreenBase.stories');
	require('../legacy/components/Common/MultiAsset/AssetList.stories');
	require('../legacy/components/Common/PinRegistrationForm.stories');
	require('../legacy/components/Delegation/DelegationConfirmation.stories');
	require('../legacy/components/Delegation/FlawedWalletScreen.stories');
	require('../legacy/components/Delegation/PoolDetailScreen.stories');
	require('../legacy/components/Delegation/StakingCenter.stories');
	require('../legacy/components/Delegation/StakingDashboard.stories');
	require('../legacy/components/FirstRun/CustomPinScreen.stories');
	require('../legacy/components/Ledger/DeviceItem/DeviceItem.stories');
	require('../legacy/components/Ledger/LedgerConnect.stories');
	require('../legacy/components/Ledger/LedgerTransportSwitchModal.stories');
	require('../legacy/components/MaintenanceScreen.stories');
	require('../legacy/components/Send/AddressReaderQR.stories');
	require('../legacy/components/Send/AssetSelectorScreen/AssetSelectorScreen.stories');
	require('../legacy/components/Send/BiometricAuthScreen.stories');
	require('../legacy/components/Send/SendScreen.stories');
	require('../legacy/components/Settings/ApplicationSettingsScreen.stories');
	require('../legacy/components/Settings/BiometricsLinkScreen.stories');
	require('../legacy/components/Settings/TermsOfServiceScreen.stories');
	require('../legacy/components/Settings/ToggleEasyConfirmationScreen.stories');
	require('../legacy/components/Transfer/TransferSummary.stories');
	require('../legacy/components/UiKit/Button.stories');
	require('../legacy/components/UiKit/Checkbox.stories');
	require('../legacy/components/UiKit/Link.stories');
	require('../legacy/components/UiKit/TextInput.stories');
	require('../legacy/components/WalletInit/ConnectNanoX/CheckNanoXScreen.stories');
	require('../legacy/components/WalletInit/ConnectNanoX/ConnectNanoXScreen.stories');
	require('../legacy/components/WalletInit/ConnectNanoX/SaveNanoXScreen.stories');
	require('../legacy/components/WalletInit/CreateWallet/CreateWalletScreen.stories');
	require('../legacy/components/WalletInit/CreateWallet/MnemonicBackupImportanceModal.stories');
	require('../legacy/components/WalletInit/CreateWallet/MnemonicCheckScreen.stories');
	require('../legacy/components/WalletInit/CreateWallet/MnemonicExplanationModal.stories');
	require('../legacy/components/WalletInit/CreateWallet/MnemonicShowScreen.stories');
	require('../legacy/components/WalletInit/RestoreWallet/ImportReadOnlyWalletScreen.stories');
	require('../legacy/components/WalletInit/RestoreWallet/RestoreWalletScreen/MnemonicInput.stories');
	require('../legacy/components/WalletInit/RestoreWallet/RestoreWalletScreen/RestoreWalletScreen.stories');
	require('../legacy/components/WalletInit/RestoreWallet/SaveReadOnlyWalletScreen.stories');
	require('../legacy/components/WalletInit/RestoreWallet/VerifyRestoredWallet.stories');
	require('../legacy/components/WalletInit/RestoreWallet/WalletAddress.stories');
	require('../legacy/components/WalletInit/RestoreWallet/WalletCredentialsScreen.stories');
	require('../legacy/components/WalletInit/WalletFreshInitScreen.stories');
	require('../legacy/components/WalletInit/WalletInitScreen.stories');
	require('../legacy/components/WalletInit/WalletNameForm.stories');
	require('../src/FirstRun/AcceptTermsOfService.stories');
	require('../src/FirstRun/CustomPinScreen.stories');
	require('../src/FirstRun/LanguagePickerScreen.stories');
	require('../src/Receive/AddressModal.stories');
	require('../src/Receive/AddressVerifyModal.stories');
	require('../src/Receive/Addresses.stories');
	require('../src/Receive/ReceiveScreen.stories');
	require('../src/SelectedWallet/WalletSelection/WalletSelectionScreen.stories');
	require('../src/Settings/ChangePassword/ChangePasswordScreen.stories');
	require('../src/Settings/ChangeWalletName/ChangeWalletName.stories');
	require('../src/Settings/RemoveWalletScreen.stories');
	require('../src/Settings/WalletSettingsScreen.stories');
	require('../src/TxHistory/ChipButton.stories');
	require('../src/TxHistory/TxHistory.stories');
	require('../src/TxHistory/TxListActionsBanner.stories');
	require('../src/components/Icon/Icon.stories');
	require('./Example/Example.stories');
}

const stories = [
	'../legacy/components/Catalyst/Catalyst.stories',
	'../legacy/components/Catalyst/VotingBanner.stories',
	'../legacy/components/Common/DangerousActionModal.stories',
	'../legacy/components/Common/ErrorModal.stories',
	'../legacy/components/Common/ExpandableItem.stories',
	'../legacy/components/Common/FingerprinScreenBase.stories',
	'../legacy/components/Common/MultiAsset/AssetList.stories',
	'../legacy/components/Common/PinRegistrationForm.stories',
	'../legacy/components/Delegation/DelegationConfirmation.stories',
	'../legacy/components/Delegation/FlawedWalletScreen.stories',
	'../legacy/components/Delegation/PoolDetailScreen.stories',
	'../legacy/components/Delegation/StakingCenter.stories',
	'../legacy/components/Delegation/StakingDashboard.stories',
	'../legacy/components/FirstRun/CustomPinScreen.stories',
	'../legacy/components/Ledger/DeviceItem/DeviceItem.stories',
	'../legacy/components/Ledger/LedgerConnect.stories',
	'../legacy/components/Ledger/LedgerTransportSwitchModal.stories',
	'../legacy/components/MaintenanceScreen.stories',
	'../legacy/components/Send/AddressReaderQR.stories',
	'../legacy/components/Send/AssetSelectorScreen/AssetSelectorScreen.stories',
	'../legacy/components/Send/BiometricAuthScreen.stories',
	'../legacy/components/Send/SendScreen.stories',
	'../legacy/components/Settings/ApplicationSettingsScreen.stories',
	'../legacy/components/Settings/BiometricsLinkScreen.stories',
	'../legacy/components/Settings/TermsOfServiceScreen.stories',
	'../legacy/components/Settings/ToggleEasyConfirmationScreen.stories',
	'../legacy/components/Transfer/TransferSummary.stories',
	'../legacy/components/UiKit/Button.stories',
	'../legacy/components/UiKit/Checkbox.stories',
	'../legacy/components/UiKit/Link.stories',
	'../legacy/components/UiKit/TextInput.stories',
	'../legacy/components/WalletInit/ConnectNanoX/CheckNanoXScreen.stories',
	'../legacy/components/WalletInit/ConnectNanoX/ConnectNanoXScreen.stories',
	'../legacy/components/WalletInit/ConnectNanoX/SaveNanoXScreen.stories',
	'../legacy/components/WalletInit/CreateWallet/CreateWalletScreen.stories',
	'../legacy/components/WalletInit/CreateWallet/MnemonicBackupImportanceModal.stories',
	'../legacy/components/WalletInit/CreateWallet/MnemonicCheckScreen.stories',
	'../legacy/components/WalletInit/CreateWallet/MnemonicExplanationModal.stories',
	'../legacy/components/WalletInit/CreateWallet/MnemonicShowScreen.stories',
	'../legacy/components/WalletInit/RestoreWallet/ImportReadOnlyWalletScreen.stories',
	'../legacy/components/WalletInit/RestoreWallet/RestoreWalletScreen/MnemonicInput.stories',
	'../legacy/components/WalletInit/RestoreWallet/RestoreWalletScreen/RestoreWalletScreen.stories',
	'../legacy/components/WalletInit/RestoreWallet/SaveReadOnlyWalletScreen.stories',
	'../legacy/components/WalletInit/RestoreWallet/VerifyRestoredWallet.stories',
	'../legacy/components/WalletInit/RestoreWallet/WalletAddress.stories',
	'../legacy/components/WalletInit/RestoreWallet/WalletCredentialsScreen.stories',
	'../legacy/components/WalletInit/WalletFreshInitScreen.stories',
	'../legacy/components/WalletInit/WalletInitScreen.stories',
	'../legacy/components/WalletInit/WalletNameForm.stories',
	'../src/FirstRun/AcceptTermsOfService.stories',
	'../src/FirstRun/CustomPinScreen.stories',
	'../src/FirstRun/LanguagePickerScreen.stories',
	'../src/Receive/AddressModal.stories',
	'../src/Receive/AddressVerifyModal.stories',
	'../src/Receive/Addresses.stories',
	'../src/Receive/ReceiveScreen.stories',
	'../src/SelectedWallet/WalletSelection/WalletSelectionScreen.stories',
	'../src/Settings/ChangePassword/ChangePasswordScreen.stories',
	'../src/Settings/ChangeWalletName/ChangeWalletName.stories',
	'../src/Settings/RemoveWalletScreen.stories',
	'../src/Settings/WalletSettingsScreen.stories',
	'../src/TxHistory/ChipButton.stories',
	'../src/TxHistory/TxHistory.stories',
	'../src/TxHistory/TxListActionsBanner.stories',
	'../src/components/Icon/Icon.stories',
	'./Example/Example.stories'
];

module.exports = {
  loadStories,
  stories,
};
