// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
	require('../legacy/components/Common/DangerousActionModal.stories');
	require('../legacy/components/Common/ErrorModal.stories');
	require('../legacy/components/Common/ExpandableItem.stories');
	require('../legacy/components/Common/FingerprinScreenBase.stories');
	require('../legacy/components/Common/PinRegistrationForm.stories');
	require('../legacy/components/Delegation/DelegationConfirmation.stories');
	require('../legacy/components/Delegation/FlawedWalletScreen.stories');
	require('../legacy/components/Delegation/PoolDetailScreen.stories');
	require('../legacy/components/Delegation/StakingCenter.stories');
	require('../legacy/components/Ledger/DeviceItem/DeviceItem.stories');
	require('../legacy/components/Ledger/LedgerConnect.stories');
	require('../legacy/components/Ledger/LedgerTransportSwitchModal.stories');
	require('../legacy/components/MaintenanceScreen.stories');
	require('../legacy/components/Send/BiometricAuthScreen.stories');
	require('../legacy/components/Transfer/TransferSummary.stories');
	require('../legacy/components/UiKit/Button.stories');
	require('../legacy/components/UiKit/Checkbox.stories');
	require('../legacy/components/UiKit/Link.stories');
	require('../legacy/components/UiKit/TextInput.stories');
	require('../src/Catalyst/Catalyst.stories');
	require('../src/Catalyst/VotingBanner.stories');
	require('../src/Dashboard/Dashboard.stories');
	require('../src/Dashboard/StakePoolInfos.stories');
	require('../src/FirstRun/CustomPinScreen/CustomPinScreen.stories');
	require('../src/FirstRun/LanguagePickerScreen/LanguagePickerScreen.stories');
	require('../src/FirstRun/TermsOfServiceScreen/TermsOfServiceScreen.stories');
	require('../src/Receive/AddressModal.stories');
	require('../src/Receive/AddressVerifyModal.stories');
	require('../src/Receive/Addresses.stories');
	require('../src/Receive/ReceiveScreen.stories');
	require('../src/SelectedWallet/WalletSelection/WalletSelectionScreen.stories');
	require('../src/Send/AddressReaderQR/AddressReaderQR.stories');
	require('../src/Send/AssetSelectorScreen/AssetSelectorScreen.stories');
	require('../src/Send/ConfirmScreen/ConfirmScreen.stories');
	require('../src/Send/SendScreen/SendScreen.stories');
	require('../src/Settings/ApplicationSettings/ApplicationSettingsScreen.stories');
	require('../src/Settings/BiometricsLink/BiometricsLinkScreen.stories');
	require('../src/Settings/ChangeLanguage/ChangeLanguageScreen.stories');
	require('../src/Settings/ChangePassword/ChangePasswordScreen.stories');
	require('../src/Settings/ChangeWalletName/ChangeWalletName.stories');
	require('../src/Settings/CustomPin/CustomPinScreen.stories');
	require('../src/Settings/RemoveWallet/RemoveWalletScreen.stories');
	require('../src/Settings/Support/SupportScreen.stories');
	require('../src/Settings/TermsOfService/TermsOfServiceScreen.stories');
	require('../src/Settings/ToggleEasyConfirmation/ToggleEasyConfirmationScreen.stories');
	require('../src/Settings/WalletSettings/WalletSettingsScreen.stories');
	require('../src/TxHistory/ChipButton.stories');
	require('../src/TxHistory/ModalInfo/ModalInfo.stories');
	require('../src/TxHistory/TxDetails/AssetList.stories');
	require('../src/TxHistory/TxHistory.stories');
	require('../src/TxHistory/TxListActionsBanner.stories');
	require('../src/WalletInit/CheckNanoX/CheckNanoXScreen.stories');
	require('../src/WalletInit/ConnectNanoX/ConnectNanoXScreen.stories');
	require('../src/WalletInit/CreateWallet/CreateWalletScreen.stories');
	require('../src/WalletInit/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.stories');
	require('../src/WalletInit/MnemonicBackupModal/MnemonicBackupImportanceModal.stories');
	require('../src/WalletInit/MnemonicCheck/MnemonicCheckScreen.stories');
	require('../src/WalletInit/MnemonicExplanationModal/MnemonicExplanationModal.stories');
	require('../src/WalletInit/MnemonicInput/MnemonicInput.stories');
	require('../src/WalletInit/MnemonicShow/MnemonicShowScreen.stories');
	require('../src/WalletInit/RestoreWallet/RestoreWalletScreen.stories');
	require('../src/WalletInit/SaveNanoX/SaveNanoXScreen.stories');
	require('../src/WalletInit/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.stories');
	require('../src/WalletInit/VerifyRestoredWallet/VerifyRestoredWalletScreen.stories');
	require('../src/WalletInit/WalletAddress/WalletAddress.stories');
	require('../src/WalletInit/WalletCredentials/WalletCredentialsScreen.stories');
	require('../src/WalletInit/WalletFreshInit/WalletFreshInitScreen.stories');
	require('../src/WalletInit/WalletInit/WalletInitScreen.stories');
	require('../src/WalletInit/WalletNameForm/WalletNameForm.stories');
	require('../src/components/Icon/Icon.stories');
	require('./Example/Example.stories');
}

const stories = [
	'../legacy/components/Common/DangerousActionModal.stories',
	'../legacy/components/Common/ErrorModal.stories',
	'../legacy/components/Common/ExpandableItem.stories',
	'../legacy/components/Common/FingerprinScreenBase.stories',
	'../legacy/components/Common/PinRegistrationForm.stories',
	'../legacy/components/Delegation/DelegationConfirmation.stories',
	'../legacy/components/Delegation/FlawedWalletScreen.stories',
	'../legacy/components/Delegation/PoolDetailScreen.stories',
	'../legacy/components/Delegation/StakingCenter.stories',
	'../legacy/components/Ledger/DeviceItem/DeviceItem.stories',
	'../legacy/components/Ledger/LedgerConnect.stories',
	'../legacy/components/Ledger/LedgerTransportSwitchModal.stories',
	'../legacy/components/MaintenanceScreen.stories',
	'../legacy/components/Send/BiometricAuthScreen.stories',
	'../legacy/components/Transfer/TransferSummary.stories',
	'../legacy/components/UiKit/Button.stories',
	'../legacy/components/UiKit/Checkbox.stories',
	'../legacy/components/UiKit/Link.stories',
	'../legacy/components/UiKit/TextInput.stories',
	'../src/Catalyst/Catalyst.stories',
	'../src/Catalyst/VotingBanner.stories',
	'../src/Dashboard/Dashboard.stories',
	'../src/Dashboard/StakePoolInfos.stories',
	'../src/FirstRun/CustomPinScreen/CustomPinScreen.stories',
	'../src/FirstRun/LanguagePickerScreen/LanguagePickerScreen.stories',
	'../src/FirstRun/TermsOfServiceScreen/TermsOfServiceScreen.stories',
	'../src/Receive/AddressModal.stories',
	'../src/Receive/AddressVerifyModal.stories',
	'../src/Receive/Addresses.stories',
	'../src/Receive/ReceiveScreen.stories',
	'../src/SelectedWallet/WalletSelection/WalletSelectionScreen.stories',
	'../src/Send/AddressReaderQR/AddressReaderQR.stories',
	'../src/Send/AssetSelectorScreen/AssetSelectorScreen.stories',
	'../src/Send/ConfirmScreen/ConfirmScreen.stories',
	'../src/Send/SendScreen/SendScreen.stories',
	'../src/Settings/ApplicationSettings/ApplicationSettingsScreen.stories',
	'../src/Settings/BiometricsLink/BiometricsLinkScreen.stories',
	'../src/Settings/ChangeLanguage/ChangeLanguageScreen.stories',
	'../src/Settings/ChangePassword/ChangePasswordScreen.stories',
	'../src/Settings/ChangeWalletName/ChangeWalletName.stories',
	'../src/Settings/CustomPin/CustomPinScreen.stories',
	'../src/Settings/RemoveWallet/RemoveWalletScreen.stories',
	'../src/Settings/Support/SupportScreen.stories',
	'../src/Settings/TermsOfService/TermsOfServiceScreen.stories',
	'../src/Settings/ToggleEasyConfirmation/ToggleEasyConfirmationScreen.stories',
	'../src/Settings/WalletSettings/WalletSettingsScreen.stories',
	'../src/TxHistory/ChipButton.stories',
	'../src/TxHistory/ModalInfo/ModalInfo.stories',
	'../src/TxHistory/TxDetails/AssetList.stories',
	'../src/TxHistory/TxHistory.stories',
	'../src/TxHistory/TxListActionsBanner.stories',
	'../src/WalletInit/CheckNanoX/CheckNanoXScreen.stories',
	'../src/WalletInit/ConnectNanoX/ConnectNanoXScreen.stories',
	'../src/WalletInit/CreateWallet/CreateWalletScreen.stories',
	'../src/WalletInit/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.stories',
	'../src/WalletInit/MnemonicBackupModal/MnemonicBackupImportanceModal.stories',
	'../src/WalletInit/MnemonicCheck/MnemonicCheckScreen.stories',
	'../src/WalletInit/MnemonicExplanationModal/MnemonicExplanationModal.stories',
	'../src/WalletInit/MnemonicInput/MnemonicInput.stories',
	'../src/WalletInit/MnemonicShow/MnemonicShowScreen.stories',
	'../src/WalletInit/RestoreWallet/RestoreWalletScreen.stories',
	'../src/WalletInit/SaveNanoX/SaveNanoXScreen.stories',
	'../src/WalletInit/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.stories',
	'../src/WalletInit/VerifyRestoredWallet/VerifyRestoredWalletScreen.stories',
	'../src/WalletInit/WalletAddress/WalletAddress.stories',
	'../src/WalletInit/WalletCredentials/WalletCredentialsScreen.stories',
	'../src/WalletInit/WalletFreshInit/WalletFreshInitScreen.stories',
	'../src/WalletInit/WalletInit/WalletInitScreen.stories',
	'../src/WalletInit/WalletNameForm/WalletNameForm.stories',
	'../src/components/Icon/Icon.stories',
	'./Example/Example.stories'
];

module.exports = {
  loadStories,
  stories,
};
