name: wallet-mobile-actions

inputs:
  node-version:
    required: true
    default: "16.19.0"
  working-directory:
    required: false
    default: "apps/wallet-mobile"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install --frozen-lockfile
      shell: bash
      working-directory: ${{ inputs.working-directory }}
