name: wallet-mobile-actions
description: "Wallet mobile actions"

inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "22.12.0"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: Build all packages
      run: ./build-packages.sh
      shell: bash
    - name: Install mobile app dependencies
      run: npm ci
      shell: bash
      working-directory: apps/mobile
