import {freeze} from 'immer'

export const DexHunterApiMocks = freeze(
  {
    swap: {
      success: {
        average_price: 1.25,
        batcher_fee: 0.1,
        cbor: 'some-cbor-data',
        communications: ['msg1', 'msg2'],
        deposits: 50,
        dexhunter_fee: 0.05,
        net_price: 1.2,
        net_price_reverse: 0.8,
        partner_code: 'partner123',
        partner_fee: 0.02,
        possible_routes: {route1: 60, route2: 40},
        splits: [
          {
            amount_in: 600,
            batcher_fee: 0.06,
            deposits: 30,
            dex: 'DEX1',
            expected_output: 750,
            expected_output_without_slippage: 740,
            fee: 0.05,
            final_price: 1.25,
            initial_price: 1.2,
            pool_fee: 0.01,
            pool_id: 'pool123',
            price_distortion: 0.02,
            price_impact: 0.03,
          },
        ],
        total_fee: 0.23,
        total_input: 1000,
        total_input_without_slippage: 980,
        total_output: 1200,
        total_output_without_slippage: 1180,
      },
    },
    sign: {
      success: {
        cbor: 'signed-tx-cbor',
        strat_id: 'strategy-123',
      },
    },
    limitEstimate: {
      success: {
        batcher_fee: 0.15,
        blacklisted_dexes: ['DEX6'],
        deposits: 100,
        dexhunter_fee: 0.07,
        net_price: 1.55,
        partner: 'partnerXYZ',
        partner_fee: 0.03,
        possible_routes: {},
        splits: [
          {
            amount_in: 700,
            batcher_fee: 0.07,
            deposits: 50,
            dex: 'DEX6',
            expected_output: 1050,
            expected_output_without_slippage: 1040,
            fee: 0.035,
            final_price: 1.55,
            initial_price: 1.5,
            pool_fee: 0.005,
            pool_id: 'poolXYZ',
            price_distortion: 0.025,
            price_impact: 0.035,
          },
        ],
        total_fee: 0.25,
        total_input: 1400,
        total_output: 2100,
      },
    },
    limit: {
      success: {
        batcher_fee: 0.15,
        cbor: 'some-cbor-data',
        deposits: 100,
        dexhunter_fee: 0.07,
        partner: 'partnerXYZ',
        partner_fee: 0.03,
        possible_routes: {routeA: 'routeA', routeB: 'routeB'},
        splits: [
          {
            amount_in: 700,
            batcher_fee: 0.07,
            deposits: 50,
            dex: 'DEX6',
            expected_output: 1050,
            expected_output_without_slippage: 1040,
            fee: 0.035,
            final_price: 1.55,
            initial_price: 1.5,
            pool_fee: 0.005,
            pool_id: 'poolXYZ',
            price_distortion: 0.025,
            price_impact: 0.035,
          },
        ],
        total_input: 1400,
        total_output: 2100,
      },
    },
    reverseEstimate: {
      success: {
        average_price: 1.25,
        batcher_fee: 0.1,
        communications: ['msg1', 'msg2'],
        deposits: 50,
        dexhunter_fee: 0.05,
        net_price: 1.2,
        net_price_reverse: 0.8,
        partner_fee: 0.02,
        possible_routes: {route1: 60, route2: 40},
        price_ab: 1.3,
        price_ba: 0.77,
        splits: [
          {
            amount_in: 600,
            batcher_fee: 0.06,
            deposits: 30,
            dex: 'DEX1',
            expected_output: 750,
            expected_output_without_slippage: 740,
            fee: 0.05,
            final_price: 1.25,
            initial_price: 1.2,
            pool_fee: 0.01,
            pool_id: 'pool123',
            price_distortion: 0.02,
            price_impact: 0.03,
          },
        ],
        total_fee: 0.23,
        total_input: 1000,
        total_input_without_slippage: 980,
        total_output: 1200,
      },
    },
    estimate: {
      success: {
        average_price: 1.35,
        batcher_fee: 0.12,
        communications: ['info1', 'info2'],
        deposits: 60,
        dexhunter_fee: 0.06,
        net_price: 1.3,
        net_price_reverse: 0.75,
        partner_code: 'partnerABC',
        partner_fee: 0.025,
        possible_routes: {routeX: 55, routeY: 45},
        splits: [
          {
            amount_in: 650,
            batcher_fee: 0.065,
            deposits: 35,
            dex: 'DEX5',
            expected_output: 877.5,
            expected_output_without_slippage: 870,
            fee: 0.04,
            final_price: 1.35,
            initial_price: 1.3,
            pool_fee: 0.007,
            pool_id: 'poolABC',
            price_distortion: 0.03,
            price_impact: 0.04,
          },
        ],
        total_fee: 0.235,
        total_output: 1755,
        total_output_without_slippage: 1740,
      },
    },
    cancel: {
      success: {
        additional_cancellation_fee: 0.05,
        cbor: 'cancel-tx-cbor-data',
      },
    },
    averagePrice: {
      success: {
        averagePrice: 1.25,
        price_ab: 1.2,
        price_ba: 0.83,
      },
    },
    tokens: {
      success: [
        {
          token_id: 'policy1tokenA',
          token_decimals: 6,
          token_policy: 'policy1',
          token_ascii: 'Token Alpha',
          ticker: 'ALPHA',
          is_verified: true,
          supply: 1000000,
          creation_date: '2023-01-01',
          price: 0.5,
        },
        {
          token_id: 'policy2tokenB',
          token_decimals: 8,
          token_policy: 'policy2',
          token_ascii: 'Token Beta',
          ticker: 'BETA',
          is_verified: false,
          supply: 500000,
          creation_date: '2023-02-15',
          price: 1.2,
        },
      ],
    },
  },
  true,
)
