export const SwapProtocol = Object.freeze({
  Cswap: 'cswap',
  Minswap_v1: 'minswap-v1',
  Minswap_v2: 'minswap-v2',
  Minswap_stable: 'minswap-stable',
  Muesliswap: 'muesliswap',
  Muesliswap_v1: 'muesliswap-v1',
  Muesliswap_v2: 'muesliswap-v2',
  Muesliswap_clp: 'muesliswap-clp',
  Muesliswap_orderbook: 'muesliswap-orderbook',
  Spectrum_v1: 'spectrum-v1',
  Sundaeswap_v1: 'sundaeswap-v1',
  Sundaeswap_v3: 'sundaeswap-v3',
  Teddy_v1: 'teddy-v1',
  Vyfi_v1: 'vyfi-v1',
  Wingriders_v1: 'wingriders-v1',
  Wingriders_v2: 'wingriders-v2',
  Wingriders_stable: 'wingriders-stable',
  Splash_v1: 'splash',
  Splash_v4: 'splash-v4',
  Splash_v5: 'splash-v5',
  Splash_v6: 'splash-v6',
  Snekfun: 'splash-degen-quad',
  Chadswap: 'chadswap',
  Cerra: 'cerra',
  Genius: 'genius',
  Unsupported: 'unsupported',
} as const)

export type SwapProtocol = (typeof SwapProtocol)[keyof typeof SwapProtocol]
