require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def pods()

  # project-specific pods

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

end

target 'emurgo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pods()

  target 'emurgoTests' do
    inherit! :complete
    # Pods for testing
  end

  target 'emurgo-staging' do
    inherit! :complete
  end

  target 'emurgo-nightly' do
    inherit! :complete
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end

end
