# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'emurgo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for emurgo
  pod 'Firebase/Core', '~> 5.14.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'

  target 'emurgoTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
