# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new staging build to TestFlight"
  lane :staging do
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    match(type: "appstore",
          app_identifier: "com.emurgo.yoroi-stag",
          verbose: true,
          git_url: "git@github.com:Emurgo/yoroi-certs.git")

    increment_build_number(xcodeproj: "emurgo.xcodeproj")
    build_app(workspace: "emurgo.xcworkspace", scheme: "emurgo-staging")
    upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
  end

  desc "Push a new mainnet build to TestFlight"
  lane :mainnet do
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    match(type: "appstore",
          app_identifier: "com.emurgo.yoroi",
          verbose: true,
          git_url: "git@github.com:Emurgo/yoroi-certs.git")

    increment_build_number(xcodeproj: "emurgo.xcodeproj")
    build_app(workspace: "emurgo.xcworkspace", scheme: "emurgo")
    upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
  end

  desc "Builds the project. Useful to verify a succesful compilation."
  lane :build do
    build_app(workspace: "emurgo.xcworkspace", scheme: "emurgo")
  end
end
