# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new staging version to Google Play"
  lane :deploy_staging do
    # Dotenv.overload '../.env.staging'
    gradle(task: "clean assembleDevRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to Google Play"
  lane :deploy_mainnet do
    # Dotenv.overload '../.env.production'
    gradle(task: "clean assembleMainRelease")
    upload_to_play_store
  end
end
