name: Create development build for devices with EAS
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        type: choice
        options:
          - all
          - ios
          - android
        default: 'all'
      branch:
        description: 'Branch to build from'
        required: false
        type: string
        default: 'develop'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  development-build:
    runs-on: macos-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || 'develop' }}

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: mobile
        run: npm ci

      - name: 🚀 Create development build
        working-directory: mobile
        run: eas build --profile dev-standalone --platform ${{ inputs.platform }} --no-wait --non-interactive

