on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: apps/wallet-mobile

      - name: Install Octopus CLI 
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
        with:
          version: latest

      - name: Create Archive 
        run: tar -czf /tmp/yoroi.tar.gz $(pwd)

      - name: Move package file 
        run: mv "/tmp/yoroi.tar.gz" yoroi.${{ steps.package-version.outputs.current-version}}.tar.gz

      - name: Push package to Octopus Deploy 
        uses: OctopusDeploy/push-package-action@v1.0.1
        with:
          packages: 'yoroi.${{ steps.package-version.outputs.current-version}}.tar.gz'
          server: https://emurgo.octopus.app
          api_key: ${{ secrets.OCTOPUS_API_KEY }}

      - name: Create release for Nightly
        uses: OctopusDeploy/create-release-action@v1.1.3
        with:
          server: https://emurgo.octopus.app
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          project: 'yoroi'
          channel: 'Nightly'
          packages: 'yoroi:${{ steps.package-version.outputs.current-version}}'
          release_number: '${{ steps.package-version.outputs.current-version}}'
          
      - name: Create release for Production
        uses: OctopusDeploy/create-release-action@v1.1.3
        with:
          server: https://emurgo.octopus.app
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          project: 'yoroi'
          channel: 'Production'
          packages: 'yoroi:${{ steps.package-version.outputs.current-version}}'
          release_number: '${{ steps.package-version.outputs.current-version}}'

