on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: ./apps/wallet-mobile/package.json

      - name: Install Octopus CLI 
        if: steps.check.outputs.changed == 'true'
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
        with:
          version: latest

      - name: Create Archive 
        run: tar -czf /tmp/yoroi.tar.gz $(pwd)

      - name: Move package file 
        if: steps.check.outputs.changed == 'true'
        run: mv "/tmp/yoroi.tar.gz" yoroi.${{ steps.check.outputs.version }}.tar.gz

      - name: Push package to Octopus Deploy 
        if: steps.check.outputs.changed == 'true'
        uses: OctopusDeploy/push-package-action@v1.0.1
        with:
          packages: 'yoroi.${{ steps.check.outputs.version }}.tar.gz'
          server: https://emurgo.octopus.app
          api_key: ${{ secrets.OCTOPUS_API_KEY }}

      - name: Create release 
        if: steps.check.outputs.changed == 'true'
        uses: OctopusDeploy/create-release-action@v1.1.3
        with:
          server: https://emurgo.octopus.app
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          project: 'yoroi'
          channel: 'Default'
          packages: 'yoroi:${{ steps.check.outputs.version }}'
          release_number: '${{ steps.check.outputs.version }}'
