name: PR Checks

on: [push]

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn flow
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
