name: Create production build for Google Play and Testflight with EAS
on:
  pull_request:
    types: [closed]
    branches:
      - production

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  preview-build:
    runs-on: macos-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: mobile
        run: npm ci

      - name: 🚀 Create production build
        run: eas build --profile production --platform all --non-interactive

      - name: 🚀 Submit build to Apple TestFlight
        run: eas submit --platform ios --profile production --non-interactive --latest

      - name: 🚀 Submit build to Android Google Play
        run: eas submit --platform android --profile production --non-interactive --latest
