name: Trigger Gitlab jobs
on:
  pull_request_review:
    types: [ submitted ]

jobs:

  Build_Request:
    if: github.event.review && (github.event.review.state == 'approved' || contains(github.event.review.body, '/check'))
    name: Requst building the app
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Trigger GitLab CI
      run: |
        echo ${{ steps.branch-name.outputs.current_branch }}

