name: Trigger Gitlab jobs
on:
  pull_request_review:
    types: [ submitted ]

jobs:

  Build_Request:
    if: github.event.review && (github.event.review.state == 'approved' || contains(github.event.review.body, '/check'))
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3

    - name: Get latest commit
      run: echo "latest_commit=$(echo ${git rev-parse HEAD})" >> $GITHUB_OUTPUT
      id: extract_latest_commit


    - name: Trigger GitLab CI
      run: echo ${{ steps.extract_latest_commit.outputs.latest_commit }}

